[package]
name = "pickem"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
sqlx = { version = "0.7.1", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.32.0", features = ["full"] }
